In [1]:
import pandas as pd
import numpy as np

In [9]:
stock_data = pd.read_excel("stock data.xlsx", sheet_name="stock prices")
stock_data

,Stock code,5,16,66,388,669,688,700,762,883,...,1044,1113,1211,1299,1810,2313,2318,2628,3968,9999
0,2022-06-30,51.65,92.70,41.00,386.0,81.85,24.80,354.4,3.71,10.36,...,36.85,55.50,314.0,85.05,13.64,95.05,53.35,13.66,52.50,144.1
1,2022-07-04,51.25,92.80,40.85,374.0,85.25,25.05,347.0,3.72,10.28,...,36.75,56.10,315.8,85.25,13.84,91.30,53.50,13.50,51.75,145.3
2,2022-07-05,50.90,93.60,40.95,370.4,87.00,24.60,348.8,3.74,10.40,...,36.55,56.05,313.6,86.00,13.36,91.00,53.30,13.54,51.45,145.1
3,2022-07-06,49.10,93.95,41.00,367.8,87.55,24.50,347.6,3.73,9.90,...,36.35,56.05,317.4,84.60,13.18,90.60,52.15,12.48,50.25,142.3
4,2022-07-07,49.65,93.35,41.20,370.6,87.95,24.40,351.6,3.73,9.84,...,36.60,56.75,325.0,84.95,13.42,89.90,52.50,12.54,48.60,139.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,2022-12-22,48.20,105.50,41.20,337.4,89.10,20.30,323.8,4.68,9.81,...,41.30,48.30,201.6,83.90,11.02,86.70,50.50,12.48,42.20,115.6
123,2022-12-23,47.90,105.90,40.90,340.0,88.25,20.55,320.2,5.00,9.81,...,40.85,48.25,194.1,86.70,10.80,86.30,50.45,12.56,41.65,113.3
124,2022-12-28,48.50,105.20,41.20,342.6,88.90,20.55,326.2,4.87,9.98,...,41.05,48.00,193.0,86.90,11.22,88.60,51.25,13.06,43.30,114.6
125,2022-12-29,48.40,104.80,41.15,340.0,87.45,20.15,335.2,4.82,9.94,...,40.60,48.00,191.0,85.10,10.86,86.50,50.70,13.06,43.20,111.3
126,2022-12-30,48.55,106.80,41.35,337.2,87.10,20.60,334.0,4.83,9.98,...,41.45,48.05,192.6,86.80,10.94,87.80,51.65,13.40,43.65,114.5

# Setting Up
SID: 1155107874

In [30]:
index1 = 1113; index2 = 688
s1 = stock_data[index1]; s2 = stock_data[index2]

# Part I: Exotic Option Pricing

## 1. Volatility and correlation calculation from historical data
### i) Calculate the realized volatilities of stock S1 and stock S2

In [79]:
def daily_rtn(daily_price): return np.log(daily_price / daily_price.shift(1))

def volatility(rtn):
    mu = np.mean(rtn)
    n = np.count_nonzero(~np.isnan(rtn))
    return np.sqrt(np.sum((rtn-mu)**2) / (n-1)) * np.sqrt(252)

u1 = daily_rtn(s1)
u2 = daily_rtn(s2)

# using own implementation
# sigma1 = volatility(u1)
# sigma2 = volatility(u2)

# using APIs
from pandas.core.frame import DataFrame
u1 = DataFrame(u1); u2 = DataFrame(u2)
sigma1 = (u1.std() * np.sqrt(252)).values[0]
sigma2 = (u2.std() * np.sqrt(252)).values[0]

print(f"Volatility of Stock {index1} and {index2} are {sigma1:.5f} and {sigma2:.5f} respectively")

Volatility of Stock 1113 and 688 are 0.25889 and 0.49836 respectively

### ii) Calculate the correlation coefficient 𝜌12 of stock S1 and stock S2

In [109]:
M_corr = u1.join(u2).corr()
rho12 = M_corr.loc[index1, index2]
print(f'correlation of Stock {index1} and {index2} are {rho12:.5f}')

correlation of Stock 1113 and 688 are 0.35814

## 2. Option pricing with Monte Carlo simulation

### i) Use a Monte Carlo scheme with time steps N = 180, i.e. delta t = T/N = 1/180. Give the answers with: (a) 1000 paths; (b) 10000 paths; (c) 100000 paths; (d) 500000 paths.

In [170]:
N = 180
T = 1
dt = 1/N
r = 3.75 * 0.01

def ABoO_payoff(S10, S11, S12, S20, S21, S22):
    B1 = np.max([S11/S10, S21/S20])
    B2 = np.max([S12/S10, S22/S20])
    A = (B1 + B2) * 0.5
    return np.max(A - 1.0, 0)

def Monte_Carlo_2_stocks(S10, S20, sigma1, sigma2, rho12, dt, N, r):
    for _ in range(N):
        x1,x2 = np.random.normal(0,1,2)
        e1 = x1; e2 = rho12 * x1 + x2 * np.sqrt(1 - rho12**2)
        dS = r * dt + sigma * e1
        pass

    
def payoff(path, s10, s20):
    payoff_list = np.zeros(path)
    for i in range(path):
        s11, s21 = Monte_Carlo_2_stocks(s10, s20,)
        s12, s22 = Monte_Carlo_2_stocks(s11, s21,)
        payoff_list[i] = ABoO_payoff(s10, s11, s12, S20, s21, s22)
        
    return payoff_list.mean()


def option_price(payoff, r, T): return np.exp(-r*T)*payoff

import time

np.random.seed(5718) # for reproduction

paths = [1000, 10000, 100000, 500000]
# paths = [1000, 10000]
avg = []

for p in paths:
    start_time = time.time()
    # simulate p times
    avg_payoff = 0
    for i in range(p):
        s10 = s1[0]; s20 = s2[0]
        s_1 = s10; s_2 = s20
        
        # simulate the first half year
        for _ in range(N//2):
            x1,x2 = np.random.normal(0,1,2)
            e1 = x1; e2 = rho12 * x1 + x2 * np.sqrt(1 - rho12**2)
            s_1 += s_1 * (r * dt + sigma1 * e1 * np.sqrt(dt))
            s_2 += s_2 * (r * dt + sigma2 * e2 * np.sqrt(dt))
        
        s11 = s_1; s21 = s_2
        
        # simulate the second half year
        for _ in range(N//2):
            x1,x2 = np.random.normal(0,1,2)
            e1 = x1; e2 = rho12 * x1 + x2 * np.sqrt(1 - rho12**2)
            s_1 += s_1 * (r * dt + sigma1 * e1 * np.sqrt(dt))
            s_2 += s_2 * (r * dt + sigma2 * e2 * np.sqrt(dt))
        
        payoff = ABoO_payoff(s10, s11, s_1, s20, s21, s_2)
        avg_payoff += payoff
    
    avg_price /= p
    avg.append(avg_price)
    print(f"time: {(time.time() - start_time)/60 } min")
    start_time = time.time()

avg

time: 0.032145702838897706 min
time: 0.30725285212198894 min
time: 2.9800064007441205 min
time: 14.798388985792796 min

[0.18915939308760746,
 0.19625396432657766,
 0.19397663408014515,
 0.1934828157794355]

In [174]:
a = np.zeros(5)
a.mean()

0.0

### ii) Use a Monte Carlo scheme with two time steps N = 2, delta t1 = delta t2 = 1⁄2. Give the answers with: (a) 1000 paths; (b) 10000 paths; (c) 100000 paths; (d) 500000 paths.

In [171]:
N = 2
T = 1
dt = 1/N

np.random.seed(5718) # for reproduction

paths = [1000, 10000, 100000, 500000]
# paths = [1000, 10000]
avg = []

for p in paths:
    
    start_time = time.time()
    # simulate p times
    avg_price = 0
    for i in range(p):
        s10 = np.log(s1[0]); s20 = np.log(s2[0])
        s_1 = s10; s_2 = s20
        
        # simulate the first half year
        for _ in range(N//2):
            x1,x2 = np.random.normal(0,1,2)
            e1 = x1; e2 = rho12 * x1 + x2 * np.sqrt(1 - rho12**2)
            s_1 *= np.exp((r - sigma1**2 / 2) * dt + sigma1 * e1 * np.sqrt(dt))
            s_2 *= np.exp((r - sigma2**2 / 2) * dt + sigma2 * e2 * np.sqrt(dt))
        
        s11 = s_1; s21 = s_2
        
        # simulate the second half year
        for _ in range(N//2):
            x1,x2 = np.random.normal(0,1,2)
            e1 = x1; e2 = rho12 * x1 + x2 * np.sqrt(1 - rho12**2)
            s_1 *= np.exp((r - sigma1**2 / 2) * dt + sigma1 * e1 * np.sqrt(dt))
            s_2 *= np.exp((r - sigma2**2 / 2) * dt + sigma2 * e2 * np.sqrt(dt))
        
        price = ABoO(s10, s11, s_1, s20, s21, s_2)
        avg_price += price
    
    avg_price /= p
    avg.append(avg_price)
    
    print(f"time: {(time.time() - start_time)/60 } min")
    start_time = time.time()

avg

time: 0.0017878333727518716 min
time: 0.014905281861623128 min
time: 0.13394258419672647 min
time: 0.6490486661593119 min

[0.19457349123325707,
 0.18953471532504193,
 0.1933780091636594,
 0.1923987436686049]

# Part II: Pricing of a structured product

In [169]:
k0 = 105 * 0.01
ki = 95 * 0.01
ac = 100 * 0.01
cp1 = 0.8 * 0.01
cp2 = 0.55 * 0.01
sigma_im = 27.1 * 0.01
s0 = 48.05

In [ ]:
def auto_call(S, Pc): return S >= Pc

def knock_in(S, Pk): return S < Pk

def expiry_payoff(Sm, K, NOM, Pk): return NOM if knock_in(Sm, Pk) or Sm >= K else NOM * Sm / K 

def

### 1. Calculate the fair price of the product F% with coupon per month CP set 1. Give the answers based on (a) 1000; (b) 10000; (c) 100000; and (d) 500000 Monte Carlo paths. In each case, record the number of times the auto-call condition is triggered. If the product is sold at an initial price of P=100%, what is the profit of the investment bank?

In [172]:
r = 3.75 * 0.01
paths = [1000]

In [31]:
print(stock_data[index1].shape)
print(stock_data[index1].shift(1).shape)
print(stock_data[index1][0])

np.sum(stock_data[index1]) - np.sum(stock_data[index1].shift(1))
print(stock_data[index1])
print(stock_data[index1].shift(1))
np.log(s1/s1.shift(1))

(127,)
(127,)
55.5
0      55.50
1      56.10
2      56.05
3      56.05
4      56.75
       ...
122    48.30
123    48.25
124    48.00
125    48.00
126    48.05
Name: 1113, Length: 127, dtype: float64
0        NaN
1      55.50
2      56.10
3      56.05
4      56.05
       ...
122    47.00
123    48.30
124    48.25
125    48.00
126    48.00
Name: 1113, Length: 127, dtype: float64

0           NaN
1      0.010753
2     -0.000892
3      0.000000
4      0.012412
         ...
122    0.027284
123   -0.001036
124   -0.005195
125    0.000000
126    0.001041
Name: 1113, Length: 127, dtype: float64